services:
  db:
    image: postgres:14
    container_name: db_obf
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - .env
    ports:
      - 5434:5342
    volumes:
      - pg_data:/var/lib/postgresql/data
    
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 10

  web_crm:
    
    build:
      context: .
    command: bash entrypoint.sh
    container_name: web_crm_obf

    volumes:
      - .:/app
    ports:
      - "8990:8989"
    env_file:
      - .env
    depends_on:
      - db
 
volumes:
  pg_data:
  